name: Node.js 16 CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    name: CI Build
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install
        run: |
          npm ci

      - name: Test
        run: |
          npm run test

      - name: Prettier check
        run: |
          npm run prettier

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
